version: "3"

vars:
  BINARY_NAME: _main
  OUT_DIR: out
  DONE_MESSAGE: "Operation Finished"

tasks:
  deps:
    desc: Run go mod tidy
    cmds:
      - cd project && go mod tidy
      - echo "{{.DONE_MESSAGE}}"

  front-dev:
    desc: Run Vite dev server
    cmds:
      - pnpm vite

  build-back:
    desc: Build backend
    cmds:
      - GOOS=darwin GOARCH=arm64 go build -o {{.OUT_DIR}}/{{.BINARY_NAME}} main.go

  dev:
    desc: Build back and run
    deps:
      - clean
      - build-back
    cmds:
      - env $(cat .env) ./out/{{.BINARY_NAME}}

  build-all:
    desc: Build both frontend and backend
    cmds:
      - pnpm vite build
      - mkdir -p {{.OUT_DIR}}
      - GOOS=darwin GOARCH=arm64 go build -o {{.OUT_DIR}}/{{.BINARY_NAME}} main.go

  clean:
    desc: Clean executables
    cmds:
      - |
        find {{.OUT_DIR}} -mindepth 1 -delete
