version: "3"

dotenv:
  - .env

#===================##===================##===================##===================##===================##===================##===================##===================#
#====== ENV ======##====== ENV ======##====== ENV ======##====== ENV ======##====== ENV ======##====== ENV ======##====== ENV ======##====== ENV ======#
#===================##===================##===================##===================##===================##===================##===================##===================#

vars:
  BINARY_NAME: _main
  OUT_DIR: out
  DONE_MESSAGE: "Operation Finished"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  #===================##===================##===================##===================##===================##===================##===================##===================#
  #====== LOCAL ======##====== LOCAL ======##====== LOCAL ======##====== LOCAL ======##====== LOCAL ======##====== LOCAL ======##====== LOCAL ======##====== LOCAL ======#
  #===================##===================##===================##===================##===================##===================##===================##===================#
  deps:
    desc: Run go mod tidy
    cmds:
      - cd project && go mod tidy
      - echo "{{.DONE_MESSAGE}}"

  front:
    desc: Run Vite dev server
    cmds:
      - pnpm vite

  build-back:
    desc: Build backend
    cmds:
      - GOOS=darwin GOARCH=arm64 go build -o {{.OUT_DIR}}/{{.BINARY_NAME}} project/src/services/main/cmd/*.go

  dev:
    desc: Build back and run
    deps:
      - clean
      - build-back
    cmds:
      - env $(cat .env) ./out/{{.BINARY_NAME}}

  prod:
    desc: Build both frontend and backend
    cmds:
      - pnpm vite build
      - mkdir -p {{.OUT_DIR}}
      - GOOS=darwin GOARCH=arm64 go build -o {{.OUT_DIR}}/{{.BINARY_NAME}} project/src/services/main/cmd/*.go
      - env $(cat .env) ./out/{{.BINARY_NAME}}

  clean:
    desc: Clean executables
    cmds:
      - |
        find {{.OUT_DIR}} -mindepth 1 -delete

  sqlc:
    desc: Generate SQLC code
    cmds:
      - go run github.com/sqlc-dev/sqlc/cmd/sqlc generate -f ./project/sqlc.yaml

  migrate-create:
    desc: "Create a migration file using goose usage: task migrate-create name=draws_and_patterns"
    requires:
      vars:
        - name
    cmds:
      - go run github.com/pressly/goose/v3/cmd/goose create {{.name}} sql

  migrate-up:
    desc: Run to sync migrations
    cmds:
      - go run github.com/pressly/goose/v3/cmd/goose up

  #===================##===================##===================##===================##===================##===================##===================##===================#
  #====== DOCKER ======##====== DOCKER ======##====== DOCKER ======##====== DOCKER ======##====== DOCKER ======##====== DOCKER ======##====== DOCKER ======##====== DOCKER ======#
  #===================##===================##===================##===================##===================##===================##===================##===================#
  start-db:
    desc: Start DB docker
    cmd: docker-compose -f ./project/src/services/main/docker/echo-inertia-dev/docker-compose.yml up -d db

  start-redis:
    desc: Start Redis docker
    cmd: docker-compose -f ./project/src/services/main/docker/echo-inertia-dev/docker-compose.yml up -d redis

  start-redis-commander:
    desc: Start Redis commander docker
    cmd: docker-compose -f ./project/src/services/main/docker/echo-inertia-dev/docker-compose.yml up -d redis-commander
